[#27] Add linter, fix style issues found by the linter
aws-beam/aws_credentials pull request #28
Opened 2021-03-04 20:51 UTC by robertoaloi

2021-03-04 21:47 UTC, mrallen1 requested changes
I don't really know much about elvis tbh, so I don't even know if this is possible to implement...

2021-03-04 21:47 UTC, mrallen1 commented on src/aws_credentials.erl
> +%%
URLs should not get whitespace in the middle of them, I should be able to copy and paste them

2021-03-05 07:57 UTC, robertoaloi commented
@mrallen1 Indeed, found the option that allows us to do that.

2021-03-05 08:45 UTC, robertoaloi commented
Merging, since the only comment has been addressed.

2021-03-05 08:45 UTC, merged